apiVersion: apps/v1
kind: Deployment
metadata:
  name: movielist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MovieList
  template:
    metadata:
      labels:
        app: MovieList
    spec:
      containers:
      - name: movielistrepos
        image: truyumcr.azurecr.io/movielistrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: movielist
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MovieList